### ISSUE TITLE
Indra Client: Unrecognized field "mt"

### ISSUE THREAD

**Issue by blang** [Lambda-3/Indra#54]
Indra Version: `lambdacube/indra:2.0.2 (docker)`
Indra Client Version: `2.0.3-rc` 24ef31f
javax.ws.rs: `2.0.1`
Jersey: `2.25.1`
Jackson: `2.8.6`

## Problem
Request gets serialized with unrecognized field "mt"

Request:
```java
RelatednessPairRequest request = new RelatednessPairRequest()
                .corpus("googlenews300neg")
                .language("EN")
                .scoreFunction(ScoreFunction.COSINE)
                .model("W2V")
                .mt(false)
                .pairs(pairs);
WebTarget webTarget = this.client.target(this.url);
RelatednessPairResponse response = webTarget.request().buildPost(Entity.entity(request, MediaType.APPLICATION_JSON_TYPE)).invoke(RelatednessPairResponse.class);
```
Debug output:
```
1 > POST http://127.0.0.1:8916/relatedness
1 > Content-Type: application/json
{"corpus":"googlenews300neg","model":"W2V","language":"EN","mt":false,"applyStopWords":null,"minWordLength":-1,"scoreFunction":"COSINE","pairs":[{"t1":"mother","t2":"love"},{"t1":"father","t2":"love"}]}

Nov 09, 2017 8:29:16 PM org.glassfish.jersey.logging.LoggingInterceptor log
INFO: 1 * Client response received on thread main
1 < 400
1 < Connection: close
1 < Content-Length: 421
1 < Content-Type: text/plain
1 < Date: Thu, 09 Nov 2017 19:29:16 GMT
Unrecognized field "mt" (class org.lambda3.indra.client.RelatednessRequest), not marked as ignorable (7 known properties: "minWordLength", "corpus", "language", "model", "pairs", "applyStopWords", "scoreFunction"])
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@8d36676; line: 1, column: 70] (through reference chain: org.lambda3.indra.client.RelatednessRequest["mt"])


javax.ws.rs.BadRequestException: HTTP 400 Bad Request

	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1011)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:819)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
```

**Comment by julsal** [comment]
Hi @blang, thanks for the notification. In fact, we are working on a new high-changed version, which is expected to be ready in few days.

I guess the commit f81cfb423f012e2476134de0617996f3067d14fe from my fork (branch pp_filter) is free of bugs. It might be useful for you now.

**Comment by blang** [comment]
Hi @julsal, thanks for the quick response. I'll have a look at the commit you mentioned.
It's pretty late in my project so i just need a stable pair relatedness.
I managed to get the request working by crafting the request by myself which was the quickest option for now.
The only question remains if the backend (lambdacube/indra:2.0.2) is stable in this situation (only pair requests)
Any experience with this version?

To use your commit f81cfb4, is a backend (docker) update necessary or does it work with lambdacube/indra:2.0.2?

Thanks,
Best,
Ben

**Comment by julsal** [comment]
Hi @blang, yes it is a large backend update. In the case that you managed to work with the current version, I don't recommend updating now. I hope up to the next week we have a new well-tested version.
Best,

**Comment by blang** [comment]
@julsal Ok thank you, i will stay with the current version. I was using a much older version of indra for development and was forced to update since the `w2v-wiki2014` dataset for the old mongo version was no longer available on the dataset server.
If the current version does not work properly, i will have to downgrade again.
Are the old python updater based datasets for the old mongo version still available online?

**Comment by julsal** [comment]
@blang For sure it is available in the one of the versions of https://github.com/Lambda-3/IndraComposed, but unfortunately I can't precise the version.

**Comment by julsal** [comment]
The new version solves this problem.
