### ISSUE TITLE
Empty documentation page

### ISSUE THREAD

**Issue by abelani** [Lambda-3/Indra#64]
Why are various documentation links pointing to a relatively empty page? Is this project alive?

**Comment by julsal** [comment]
Hi @abelani, thanks for your message. Yes, the project is still alive. We found a point of stability in the current set of features, this is why we didn't have new commits recently. However, new features are planned (and are also welcome from PR). In relation to the documentation, we started migrating it to a read-the-docs format but didn't finish yet. I'll check with my colleagues how we can speed up this deliver. Nonetheless, if you have any question, I can give you some support from here.
