### ISSUE TITLE
400 Client Error: Bad Request for url

### ISSUE THREAD

**Issue by efiltz** [Lambda-3/Indra#67]
Hi, 
i installed Indra using IndraComposed and have problems to get the "nearest neighbors" running. While pair relatedness, OTM nearest neighbors work, i get an error for the nearest neighbors relatedness:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:8916/neighbors/relatedness`

The code i am using is as follows: 

```
data = {'corpus': 'wiki-2018', 
             'model': 'W2V', 
             'language': 'EN', 
             'topk' : '3', 
             'terms': ['house', 'engine']
           }
res = requests.post("http://localhost:8916/neighbors/vectors", data = json.dumps(data), headers = headers)
res.raise_for_status()
print('[Nearest neighbor vectors]', res.json())
```

**Comment by julsal** [comment]
Hi @efiltz, I can't make a test now, but I guess the problem is because you didn't define a scoreFunction. Include "scoreFunction": "COSINE" in your json to test.

**Comment by efiltz** [comment]
That was it, thanks! I took the code from the paper and did not think of the scoreFunction.
