### ISSUE TITLE
IndraComposed connection refused while downloading Model

### ISSUE THREAD

**Issue by szkaus** [Lambda-3/Indra#70]
Hi I am a PhD student working with semantic relatedness. I am trying to use IndraComposed by following the instructions given here: https://github.com/Lambda-3/IndraComposed

However, while I am trying to download the model with `/downloader.sh w2v-en-googlenews` I am getting the connection refusal error. The full trace is below:

```
Downloading http://data.lambda3.org/indra/dumps/w2v-en-wiki-2018.annoy.tar.gz ..
--2020-02-05 18:19:09--  http://data.lambda3.org/indra/dumps/w2v-en-wiki-2018.annoy.tar.gz
Resolving data.lambda3.org (data.lambda3.org)... 88.99.85.116
Connecting to data.lambda3.org (data.lambda3.org)|88.99.85.116|:80... failed: Connection refused.
Extracting w2v-en-wiki-2018.annoy.tar.gz
tar: w2v-en-wiki-2018.annoy.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```
Can you kindly provide a solution?

**Comment by julsal** [comment]
Dear @szkaus, thanks for your interest in Indra. The current server storing the model is unaccessable, but we are migrating the models to another server. I might have it ready for you tonight (CET).

**Comment by szkaus** [comment]
Hi Juliano,

Thanks a lot. I already read the paper. Great to hear that I might have access to the models soon. The services would be really useful for my research as a benchmark.

**Comment by julsal** [comment]
Dear @szkaus, I've updated the `IndraComposed` repository to download the models from the new server. Don't hesitate to contact us again in the case of troubles. Remember to pull the latest version from `IndraComposed` before starting downloading.

**Comment by szkaus** [comment]
Just tested it. It's working! Thanks so much. Hope you have all the models there, I will try to compare with at least three models from there. Definitely, this is a great resource and We will strongly cite and recommend in our work.
